config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :tickets, only: :create
    end
  end

  resources :tickets, only: %i[index show], controller: 'tickets/tickets'

  root to: 'tickets/tickets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy
  accepts_nested_attributes_for :excavator

  enum request_type: { normal: 'Normal' }
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TicketsController < ApiController
      def create
        @result = Tickets::Create.call(json: request.body.read)
        render json: response_message, status: response_status
      end
    end
  end
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ActionController::API
  rescue_from StandardError, with: :server_error

  private

  def server_error(exception)
    Rails.logger.error(exception)
    render json: { error: 'Internal Server Error', status: '500' },
           status: :internal_server_error
  end

  def response_message
    { message: @result.value[:message], status: @result.value[:status] }
  end

  def response_status
    @result.value[:status]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/tickets/tickets_controller.rb
class Tickets::TicketsController < ApplicationController
  def index
    @pagy, @records = pagy(Ticket.all)
    render 'tickets/index', locals: { tickets: @records } if stale?(@records)
  end

  def show
    @record = Ticket.find(params[:id])
    render 'tickets/show', locals: { ticket: @record } if stale?(@record)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcavatorsCrew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_map.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
        integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
        crossorigin=""/>

  <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
          integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
          crossorigin=""></script>
<% end %>

<div id="map" class="h-full"></div>

<%= javascript_tag do %>
  let map = L.map('map');
  let polygon = L.polygon(<%= polygon %>, { color: 'red' }).addTo(map);

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
  maxZoom: 18,
  id: 'mapbox/streets-v11',
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
  '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
  'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
  tileSize: 512,
  zoomOffset: -1
  }).addTo(map);

  map.fitBounds(polygon.getBounds());
<% end %>

app/views/tickets/_ticket.html.erb
<tr>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= ticket.id %></td>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= ticket.request_number %></td>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= ticket.request_type %></td>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= ticket.sequence_number %></td>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= ticket.response_due_at %></td>
  <td class="w-1/12 text-left py-3 px-4 text-xs"><%= link_to ticket do %><button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">View</button><% end %></td>
</tr>

app/views/tickets/index.html.erb
<div class="md:px-32 py-8 w-full content-center">
    <div class="flex">
        <h1 class="text-3xl">
            Tickets
        </h1>
    </div>
  <div class="shadow overflow-hidden rounded border-b border-gray-200">
    <table class="min-w-full bg-white w-12">
      <thead class="bg-gray-800 text-white">
        <tr>
          <th class="w-1/12 text-left py-3 px-4 text-xs">ID</th>
          <th class="w-1/12 text-left py-3 px-4 text-xs">Request Number</th>
          <th class="w-1/12 text-left py-3 px-4 text-xs">Sequence Number</th>
          <th class="w-1/12 text-left py-3 px-4 text-xs">Request Type</td>
          <th class="w-1/12 text-left py-3 px-4 text-xs">Response Due</td>
          <th class="w-1/12 text-left py-3 px-4 text-xs">Action</td>
        </tr>
      </thead>
    <tbody class="text-gray-700">
    <%= render partial: 'tickets/ticket', collection: tickets %>
    </tbody>
    </table>
  </div>
  <div class="w-1/3 p-2">
  <%== pagy_nav(@pagy) %>
 </div>
</div>

app/views/tickets/show.html.erb
<div class="flex mb-4">
  <div class="w-5/12 h-screen">
    <%= render 'tickets/map', polygon: ticket.geo_polygon %>
  </div>
  <div class="w-7/12 bg-white h-64 px-10 py-10">
    <a href="<%= tickets_url %>">← Back to tickets</a>
    <h2 class="pt-4 text-2xl">Ticket <%= ticket.id %></h2>

    <div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md">
      <table>
        <tr>
          <td class="pr-3">Response Due:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.response_due_at %></span></td>
        </tr>
        <tr>
          <td>Request Number:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.request_number %></span></td>
        </tr>
        <tr>
          <td>Sequence Number:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.sequence_number %></span></td>
        </tr>
        <tr>
          <td>Request Type:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.request_type %></span></td>
        </tr>
        <tr>
          <td>Primary Service Code Area:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.primary_service_area_code %></span></td>
        </tr>
        <tr>
          <td class="pr-3">Additional Serivce Code Areas:</td>
          <td><span class="text-xl text-gray-700 font-bold"><%= ticket.additional_service_area_codes.join(',') %></span>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>